### ISSUE TITLE
Field is not getting saved in record unless it is _id

### ISSUE THREAD

**Issue by iammoen** [TheRoSS/mongodb-autoincrement#2]
I believe this is due to line 71 in mongodb-autoincrement.js where the line reads:
doc._id = result;

It should be something more like doc.fieldName = result I believe.

I haven't ever reported something so sorry if this isn't the proper way to do it!

**Comment by matogertel** [comment]
Yup just found the same issue!

**Comment by melodylife** [comment]
Found the same issue. Could you please update the package in npm with the patch ?

**Comment by natan88** [comment]
I found two causes for this error, the first one is on the line 71 as mentioned iammoen, I changed to doc[fieldName] = result; 

The second cause was in line 125, changed callback(null, result.seq); for callback(null, result.value.seq);

Verjuice if you can update the NPM package with the mentioned fixes.

**Comment by plusk01** [comment]
I didn't have a problem with iammoen suggestion on line 71, but I solved the issue by doing what natan88 had done on line 125.

**Comment by carloscant** [comment]
```
doc[fieldName] = result; 
```
in line 71 solved the issue for me.

**Comment by LeandroFavero** [comment]
I got the same problem. Fix changing line 125 like natan88 said.

**Comment by TheRoSS** [comment]
fixed
